//
//  ProducivilityPageInteractor.swift
//  Improcess
//
//  Created by MuMhu on 17/2/2562 BE.
//  Copyright (c) 2562 Kittitat Boonkarn. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol ProducivilityPageBusinessLogic
{
    func doSomething(request: ProducivilityPage.Something.Request)
}

protocol ProducivilityPageDataStore
{
    //var name: String { get set }
}

class ProducivilityPageInteractor: ProducivilityPageBusinessLogic, ProducivilityPageDataStore
{
    var presenter: ProducivilityPagePresentationLogic?
    var worker: ProducivilityPageWorker?
    //var name: String = ""
    
    // MARK: Do something
    
    func doSomething(request: ProducivilityPage.Something.Request)
    {
        worker = ProducivilityPageWorker()
        worker?.doSomeWork()
        
        let response = ProducivilityPage.Something.Response()
        presenter?.presentSomething(response: response)
    }
}
