//
//  ProducivilityPagePresenter.swift
//  Improcess
//
//  Created by MuMhu on 17/2/2562 BE.
//  Copyright (c) 2562 Kittitat Boonkarn. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol ProducivilityPagePresentationLogic
{
    func presentProducivility(response: ProducivilityPage.Producivility.Response)
}

class ProducivilityPagePresenter: ProducivilityPagePresentationLogic
{
    weak var viewController: ProducivilityPageDisplayLogic?
    
    // MARK: Do something
    
    func presentProducivility(response: ProducivilityPage.Producivility.Response)
    {
        let viewModel = ProducivilityPage.Producivility.ViewModel(tasksProducivility: response.tasksProducivility)
        viewController?.displayProducivility(viewModel: viewModel)
        
    }
}
