//
//  ProducivilityPageInteractor.swift
//  Improcess
//
//  Created by MuMhu on 17/2/2562 BE.
//  Copyright (c) 2562 Kittitat Boonkarn. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol ProducivilityPageBusinessLogic
{
    var tasks: [ProjectTask]? {get}
     func getAllTaskProducivility()
}

protocol ProducivilityPageDataStore
{
    var projectDetail: ProjectDetail? {get set}
    var tasks: [ProjectTask]? {get set}
}

class ProducivilityPageInteractor: ProducivilityPageBusinessLogic, ProducivilityPageDataStore
{
    var tasks: [ProjectTask]?
    var projectDetail: ProjectDetail?

    var presenter: ProducivilityPagePresentationLogic?
    var worker: ProducivilityPageWorker?
    //var name: String = ""
    
    func getAllTaskProducivility(){
        worker = ProducivilityPageWorker()
        worker?.getAllTasksProducivility(project: projectDetail!, tasks: tasks!, completionHandler:  { (lists) in
            let response = ProducivilityPage.Producivility.Response(tasksProducivility: lists)
            self.presenter?.presentProducivility(response: response)
        })
    }
}
