//
//  ProducivilityPagePresenter.swift
//  Improcess
//
//  Created by MuMhu on 17/2/2562 BE.
//  Copyright (c) 2562 Kittitat Boonkarn. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol ProducivilityPagePresentationLogic
{
    func presentSomething(response: ProducivilityPage.Something.Response)
}

class ProducivilityPagePresenter: ProducivilityPagePresentationLogic
{
    weak var viewController: ProducivilityPageDisplayLogic?
    
    // MARK: Do something
    
    func presentSomething(response: ProducivilityPage.Something.Response)
    {
        let viewModel = ProducivilityPage.Something.ViewModel()
        viewController?.displaySomething(viewModel: viewModel)
    }
}
