//
//  LoginPagePresenter.swift
//  Improcess
//
//  Created by MuMhu on 10/10/2561 BE.
//  Copyright (c) 2561 Kittitat Boonkarn. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol LoginPagePresentationLogic
{
  func presentAuthStatus(response: LoginPage.Auth.Response)
}

class LoginPagePresenter: LoginPagePresentationLogic
{
  weak var viewController: LoginPageDisplayLogic?
  
  // MARK: Do something
  
  func presentAuthStatus(response: LoginPage.Auth.Response)
  {
    let viewModel = LoginPage.Auth.ViewModel(isError: response.isError, errorMessage: response.errorMessage)
    viewController?.displayAuth(viewModel: viewModel)
  }
}
