//
//  LoginPageWorker.swift
//  Improcess
//
//  Created by MuMhu on 10/10/2561 BE.
//  Copyright (c) 2561 Kittitat Boonkarn. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit
import FirebaseAuth

class LoginPageWorker
{
    func authentication(username: String!, password: String!, completionHandler: @escaping (Bool, String?) -> Void){
    Auth.auth().signIn(withEmail: username!, password: password!) { (user, error) in
        if error != nil {
            completionHandler(true, "Wrong username or password!")
        }else{
            completionHandler(false, nil)
        }
    }
        
  }
    
}
