//
//  LoginPageViewController.swift
//  Improcess
//
//  Created by MuMhu on 10/10/2561 BE.
//  Copyright (c) 2561 Kittitat Boonkarn. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol LoginPageDisplayLogic: class
{
    func displayAuth(viewModel: LoginPage.Auth.ViewModel)
}

class LoginPageViewController: UIViewController, LoginPageDisplayLogic, UITextFieldDelegate
{
    var interactor: LoginPageBusinessLogic?
    var router: (NSObjectProtocol & LoginPageRoutingLogic & LoginPageDataPassing)?
    
    override init(nibName nibNameOrNil: String?, bundle nibBundleOrNil: Bundle?)
    {
        super.init(nibName: nibNameOrNil, bundle: nibBundleOrNil)
        setup()
    }
    
    required init?(coder aDecoder: NSCoder)
    {
        super.init(coder: aDecoder)
        setup()
    }
    
    // MARK: Setup
    
    private func setup()
    {
        let viewController = self
        let interactor = LoginPageInteractor()
        let presenter = LoginPagePresenter()
        let router = LoginPageRouter()
        viewController.interactor = interactor
        viewController.router = router
        interactor.presenter = presenter
        presenter.viewController = viewController
        router.viewController = viewController
        router.dataStore = interactor
    }
    
    // MARK: Routing
    
    override func prepare(for segue: UIStoryboardSegue, sender: Any?)
    {
        if let scene = segue.identifier {
            let selector = NSSelectorFromString("routeTo\(scene)WithSegue:")
            if let router = router, router.responds(to: selector) {
                router.perform(selector, with: segue)
            }
        }
    }
    
    // MARK: View lifecycle
    
    override func viewDidLoad()
    {
        super.viewDidLoad()
        self.hideKeyboardWhenTappedAround()
        self.usernameTextfield.delegate = self
        self.passwordTextfield.delegate = self
    }
    
    // MARK: Do something
    @IBOutlet weak var usernameTextfield: UITextField!
    @IBOutlet weak var passwordTextfield: UITextField!
    
    
    func textFieldShouldReturn(_ textField: UITextField) -> Bool {
        textField.resignFirstResponder()
        return true
    }
    
    func displayErrorMessage(message: String){
        let alert = UIAlertController(title: "Error", message: message, preferredStyle: .alert)
        alert.addAction(UIAlertAction(title: "OK", style: .default, handler: nil))
        self.present(alert, animated: true, completion: nil)
    }
    
    
    @IBAction func handleLogin(_ sender: Any) {
        let username = usernameTextfield.text ?? ""
        let password = passwordTextfield.text ?? ""
        let request = LoginPage.Auth.Request(username: username, password: password)
        interactor?.login(request: request)
    }
    
    func displayAuth(viewModel: LoginPage.Auth.ViewModel)
    {
        if viewModel.isError != true {
            performSegue(withIdentifier: "Login", sender: nil)
        }
        else {
            displayErrorMessage(message: viewModel.errorMessage ?? "Somethings went wrong!")
        }
    }
    
}
