//
//  InitProjectInteractor.swift
//  Improcess
//
//  Created by MuMhu on 21/10/2561 BE.
//  Copyright (c) 2561 Kittitat Boonkarn. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol InitProjectBusinessLogic
{
    var proJectName: String { get set }
    var proJectDetails: String { get set }
}

protocol InitProjectDataStore
{
    var proJectName: String { get set }
    var proJectDetails: String { get set }
}

class InitProjectInteractor: InitProjectBusinessLogic, InitProjectDataStore
{
    var proJectName: String = ""
    var proJectDetails: String = ""
    var presenter: InitProjectPresentationLogic?
    var worker: InitProjectWorker?
    //var name: String = ""

}
