//
//  InitProjectWorker.swift
//  Improcess
//
//  Created by MuMhu on 21/10/2561 BE.
//  Copyright (c) 2561 Kittitat Boonkarn. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit
import Firebase

class InitProjectWorker
{
    func checkForEveryProjectName(name: String) -> Bool
    {
//        let uid = Auth.auth().currentUser?.uid
//        Database.database().reference().child(uid!).child("project").observe(.value) { (DataSnapshot) in
//            print(DataSnapshot.key ?? "KUY")
//        }
        return true
    }
}

