//
//  InitSummaryInteractor.swift
//  Improcess
//
//  Created by MuMhu on 21/10/2561 BE.
//  Copyright (c) 2561 Kittitat Boonkarn. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol InitSummaryBusinessLogic
{
    var steps: [AddSteps] {get set}
}

protocol InitSummaryDataStore
{
    var proJectName: String? { get set }
    var proJectDetails: String { get set }
    var steps: [AddSteps] {get set}
}

class InitSummaryInteractor: InitSummaryBusinessLogic, InitSummaryDataStore
{
    var proJectName: String?
    
    var proJectDetails: String = ""
    
    var steps = [AddSteps]()
    var presenter: InitSummaryPresentationLogic?
    var worker: InitSummaryWorker?
    //var name: String = ""
    
    // MARK: Do something
}
