//
//  InitSummaryViewController.swift
//  Improcess
//
//  Created by MuMhu on 21/10/2561 BE.
//  Copyright (c) 2561 Kittitat Boonkarn. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol InitSummaryDisplayLogic: class
{
  func displaySomething(viewModel: InitSummary.Something.ViewModel)
}

class InitSummaryViewController: UIViewController, InitSummaryDisplayLogic
{
  var interactor: InitSummaryBusinessLogic?
  var router: (NSObjectProtocol & InitSummaryRoutingLogic & InitSummaryDataPassing)?

    @IBOutlet weak var labelss: UILabel!
    
  // MARK: Object lifecycle
  
  override init(nibName nibNameOrNil: String?, bundle nibBundleOrNil: Bundle?)
  {
    super.init(nibName: nibNameOrNil, bundle: nibBundleOrNil)
    setup()
  }
  
  required init?(coder aDecoder: NSCoder)
  {
    super.init(coder: aDecoder)
    setup()
  }
  
  // MARK: Setup
  
  private func setup()
  {
    let viewController = self
    let interactor = InitSummaryInteractor()
    let presenter = InitSummaryPresenter()
    let router = InitSummaryRouter()
    viewController.interactor = interactor
    viewController.router = router
    interactor.presenter = presenter
    presenter.viewController = viewController
    router.viewController = viewController
    router.dataStore = interactor
  }
  
  // MARK: Routing
  
  override func prepare(for segue: UIStoryboardSegue, sender: Any?)
  {
    if let scene = segue.identifier {
      let selector = NSSelectorFromString("routeTo\(scene)WithSegue:")
      if let router = router, router.responds(to: selector) {
        router.perform(selector, with: segue)
      }
    }
  }
  
  // MARK: View lifecycle
  
  override func viewDidLoad()
  {
    super.viewDidLoad()
    doSomething()
  }
  
  // MARK: Do something
  
  //@IBOutlet weak var nameTextField: UITextField!
  
  func doSomething()
  {
    let request = InitSummary.Something.Request()
    interactor?.doSomething(request: request)
  }
  
  func displaySomething(viewModel: InitSummary.Something.ViewModel)
  {
    //nameTextField.text = viewModel.name
  }
}
