//
//  InitSummaryModels.swift
//  Improcess
//
//  Created by MuMhu on 21/10/2561 BE.
//  Copyright (c) 2561 Kittitat Boonkarn. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

enum InitSummary
{
  enum Step
  {
    struct Request
    {
    }
    struct Response
    {
    }
    struct ViewModel
    {
        var name: String!
        var description: String!
        var index: Int!
        
        init(myName: String?, myIndex: Int?) {
            name = myName
            index = myIndex
            description = ""
        }
    }
  }
}

struct AddSteps
{
    var name: String!
    var description: String!
    var index: Int!
}
