//
//  ProjectPageInteractor.swift
//  Improcess
//
//  Created by MuMhu on 30/10/2561 BE.
//  Copyright (c) 2561 Kittitat Boonkarn. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol ProjectPageBusinessLogic
{
    var project: ProjectDetail? {get set}
    func receiveProject()
}

protocol ProjectPageDataStore
{
    var project: ProjectDetail? {get set}
}

class ProjectPageInteractor: ProjectPageBusinessLogic, ProjectPageDataStore
{
    var presenter: ProjectPagePresentationLogic?
    var worker: ProjectPageWorker?
    var project: ProjectDetail?
    // MARK: Do something
    
    //    func doSomething(request: ProjectPage.Something.Request)
    //    {
    //        worker = ProjectPageWorker()
    //        worker?.doSomeWork()
    //
    //        let response = ProjectPage.Something.Response()
    //        presenter?.presentSomething(response: response)
    //    }
    
    func receiveProject() {
        let response = ProjectPage.Project.Response(project: project!)
        presenter?.presentProject(response: response)
    }
    
}
