//
//  DashboardWorker.swift
//  Improcess
//
//  Created by MuMhu on 9/4/2562 BE.
//  Copyright (c) 2562 Kittitat Boonkarn. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit
import Firebase

class DashboardWorker
{
    func deleteProject(name: String)
    {
        let uid = Auth.auth().currentUser?.uid
        Database.database().reference().child(uid!).child("projects").child(name).removeValue()
    }
    
}
