//
//  AddProjectDefectsInteractor.swift
//  Improcess
//
//  Created by MuMhu on 25/10/2561 BE.
//  Copyright (c) 2561 Kittitat Boonkarn. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol AddProjectDefectsBusinessLogic
{
    var proJectName: String? { get set }
    var proJectDetails: String { get set }
    var steps: [AddSteps] {get set}
    var defects: [Defect] {get set}
    func uploadDataToFirebase()
}

protocol AddProjectDefectsDataStore
{
    var proJectName: String? { get set }
    var proJectDetails: String { get set }
    var steps: [AddSteps] {get set}
}

class AddProjectDefectsInteractor: AddProjectDefectsBusinessLogic, AddProjectDefectsDataStore
{
    var proJectName: String?
    var proJectDetails: String = ""
    var steps: [AddSteps] = []
    var defects: [Defect] = []
    var presenter: AddProjectDefectsPresentationLogic?
    var worker: AddProjectDefectsWorker?
    //var name: String = ""
    
    // MARK: Do something
    
    func uploadDataToFirebase()
    {
        
        worker = AddProjectDefectsWorker()
        worker?.postToFirebase(projectName: proJectName!, projectDescription: proJectDetails, steps: steps, defects: defects)

        presenter?.presentAlert()
    }
}
