//
//  AddProjectDefectsPresenter.swift
//  Improcess
//
//  Created by MuMhu on 25/10/2561 BE.
//  Copyright (c) 2561 Kittitat Boonkarn. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol AddProjectDefectsPresentationLogic
{
    func presentAlert()
}

class AddProjectDefectsPresenter: AddProjectDefectsPresentationLogic
{
    weak var viewController: AddProjectDefectsDisplayLogic?
    
    // MARK: Do something
    
    func presentAlert()
    {
        viewController?.displayAlert()
    }
}
