//
//  AddProjectDefectsInteractor.swift
//  Improcess
//
//  Created by MuMhu on 25/10/2561 BE.
//  Copyright (c) 2561 Kittitat Boonkarn. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol AddProjectDefectsBusinessLogic
{
    func doSomething(request: AddProjectDefects.Something.Request)
}

protocol AddProjectDefectsDataStore
{
    var proJectName: String? { get set }
    var proJectDetails: String { get set }
    var steps: [AddSteps] {get set}
}

class AddProjectDefectsInteractor: AddProjectDefectsBusinessLogic, AddProjectDefectsDataStore
{
    var proJectName: String?
    
    var proJectDetails: String = ""
    
    var steps: [AddSteps] = []
    
    var presenter: AddProjectDefectsPresentationLogic?
    var worker: AddProjectDefectsWorker?
    //var name: String = ""
    
    // MARK: Do something
    
    func doSomething(request: AddProjectDefects.Something.Request)
    {
        
        worker = AddProjectDefectsWorker()
        worker?.doSomeWork()
        
        print(steps)
        let response = AddProjectDefects.Something.Response()
        presenter?.presentSomething(response: response)
    }
}
