//
//  TaskPageInteractor.swift
//  Improcess
//
//  Created by MuMhu on 17/12/2561 BE.
//  Copyright (c) 2561 Kittitat Boonkarn. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol TaskPageBusinessLogic
{
    func loadDropDown()
}

protocol TaskPageDataStore
{
    var phraseList: [PhraseTypeList] {get set}
    var defectList: [DefectTypeList] {get set}
    var selectedTask: ProjectTask? {get set}
}

class TaskPageInteractor: TaskPageBusinessLogic, TaskPageDataStore
{
    var presenter: TaskPagePresentationLogic?
    var worker: TaskPageWorker?
    var phraseList: [PhraseTypeList] = []
    var defectList: [DefectTypeList] = []
    var selectedTask: ProjectTask?
    
    // MARK: Do something
    
    func loadDropDown()
    {
        let response = TaskPage.DropDown.Response(phraseList: phraseList, defectList: defectList)
        presenter?.presentDropDown(response: response)
    }
}
