//
//  TaskPageModels.swift
//  Improcess
//
//  Created by MuMhu on 17/12/2561 BE.
//  Copyright (c) 2561 Kittitat Boonkarn. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

enum TaskPage
{
    enum ProjectData
    {
        struct Request
        {
        }
        struct Response
        {
            var phrases: [PhraseList]
        }
        struct ViewModel
        {
            var phrases: [PhraseList]
        }
    }
    
    enum DropDown
    {
        struct Request
        {
        }
        struct Response
        {
            var phraseList: [PhraseTypeList]
            var defectList: [DefectTypeList]
        }
        struct ViewModel
        {
            var phraseList: [PhraseTypeList]
            var defectList: [DefectTypeList]
        }
    }
}

struct KeyMetricList {
    var name: String?
}

struct DefectList{
    var name: String?
    var timer: Int?
    var detail: String?
}

struct PhraseList {
    var name: String?
    var timer: Int?
    var detail: String?
}
