//
//  TaskPagePresenter.swift
//  Improcess
//
//  Created by MuMhu on 17/12/2561 BE.
//  Copyright (c) 2561 Kittitat Boonkarn. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol TaskPagePresentationLogic
{
    func presentDropDown(response: TaskPage.DropDown.Response)
}

class TaskPagePresenter: TaskPagePresentationLogic
{
    weak var viewController: TaskPageDisplayLogic?
    
    // MARK: Do something
    
    func presentDropDown(response: TaskPage.DropDown.Response)
    {
        let viewModel = TaskPage.DropDown.ViewModel(phraseList: response.phraseList, defectList: response.defectList)
        viewController?.displayDropDown(viewmodel: viewModel)
    }
}
