//
//  LandingPageModels.swift
//  Improcess
//
//  Created by MuMhu on 16/10/2561 BE.
//  Copyright (c) 2561 Kittitat Boonkarn. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

enum LandingPage
{
    
    enum Project
    {
        struct Request
        {
            var uid: String?
        }
        struct Response
        {
            var projectsName: [ProjectDetail]?
//            var tasks: Int?
        }
        struct ViewModel
        {
            var projectsName: [ProjectDetail]?
//            var tasks: Int?
        }
    }
    
    enum Date
    {
        struct Request
        {
        }
        struct Response
        {
            var date: String?
        }
        struct ViewModel
        {
            var date: String?
        }
    }
}

struct ProjectDetail {
    var name: String?
    var timestamp: Int?
    var detail: String?
    var imagePath: String?
    var taskQuantity: Int?
    
    init(thisName: String, thisTimestamp: Int, thisDetail: String, thisImagePath: String, thisTask: Int?) {
        name = thisName
        timestamp = thisTimestamp
        detail = thisDetail
        imagePath = thisImagePath
        taskQuantity = thisTask
    }
}
