//
//  LandingPagePresenter.swift
//  Improcess
//
//  Created by MuMhu on 16/10/2561 BE.
//  Copyright (c) 2561 Kittitat Boonkarn. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol LandingPagePresentationLogic
{
    func presentDate(response: LandingPage.Date.Response)
    func presentProjects(response: LandingPage.Project.Response)
}

class LandingPagePresenter: LandingPagePresentationLogic
{
    weak var viewController: LandingPageDisplayLogic?
    // MARK: Do something
    
    func presentDate(response: LandingPage.Date.Response)
    {
        let viewModel = LandingPage.Date.ViewModel(date: response.date)
        viewController?.displayDate(viewModel: viewModel)
    }
    
    func presentProjects(response: LandingPage.Project.Response) {
        var projects = response.projectsName
        projects?.sort(by: { (firstPro, secPro) -> Bool in
            return firstPro.timestamp! > secPro.timestamp!
        })
        let viewModel = LandingPage.Project.ViewModel(projectsName: projects)
        viewController?.displayProjects(viewModel: viewModel)
    }
}
