//
//  LandingPageRouter.swift
//  Improcess
//
//  Created by MuMhu on 16/10/2561 BE.
//  Copyright (c) 2561 Kittitat Boonkarn. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

@objc protocol LandingPageRoutingLogic
{
    func routeToProjectPage(segue: UIStoryboardSegue?)
}

protocol LandingPageDataPassing
{
    var dataStore: LandingPageDataStore? { get }
}

class LandingPageRouter: NSObject, LandingPageRoutingLogic, LandingPageDataPassing
{
    weak var viewController: LandingPageViewController?
    var dataStore: LandingPageDataStore?
    
    // MARK: Routing
    
    func routeToProjectPage(segue: UIStoryboardSegue?)
    {
      if let segue = segue {
        let destinationVC = segue.destination as! ProjectPageViewController
        var destinationDS = destinationVC.router!.dataStore!
        passDataToProjectPage(source: dataStore!, destination: &destinationDS)
      } else {
        let storyboard = UIStoryboard(name: "Main", bundle: nil)
        let destinationVC = storyboard.instantiateViewController(withIdentifier: "ProjectPage") as! ProjectPageViewController
        var destinationDS = destinationVC.router!.dataStore!
        passDataToProjectPage(source: dataStore!, destination: &destinationDS)
        navigateToProjectPage(source: viewController!, destination: destinationVC)
      }
    }
    
//     MARK: Navigation
    
    func navigateToProjectPage(source: LandingPageViewController, destination: ProjectPageViewController)
    {
      source.show(destination, sender: nil)
    }
    
//     MARK: Passing data
    
    func passDataToProjectPage(source: LandingPageDataStore, destination: inout ProjectPageDataStore)
    {
      destination.project = source.project
    }
}
