//
//  LandingPageModels.swift
//  Improcess
//
//  Created by MuMhu on 16/10/2561 BE.
//  Copyright (c) 2561 Kittitat Boonkarn. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

enum LandingPage
{
    
    enum Project
    {
        struct Request
        {
            var projectName: String?
        }
        struct Response
        {
            var projectName: String?
            var tasks: Int?
        }
        struct ViewModel
        {
            var projectName: String?
            var tasks: Int?
        }
    }
    
    enum Date
    {
        struct Request
        {
        }
        struct Response
        {
            var date: String?
        }
        struct ViewModel
        {
            var date: String?
        }
    }
}
