//
//  LandingPageWorker.swift
//  Improcess
//
//  Created by MuMhu on 16/10/2561 BE.
//  Copyright (c) 2561 Kittitat Boonkarn. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit
import Firebase

class LandingPageWorker
{
    func requestProjectFormFirebase(uid: String!, completionHandler: @escaping([ProjectDetail]) -> Void)
    {
        var projects = [ProjectDetail]()
        Database.database().reference().child(uid!).child("project").observeSingleEvent(of: .value) { (snapshot) in
            if let projectsDic = snapshot.value as? [String : AnyObject]{
                for project in projectsDic{
                    let dict = project.value as! [String: AnyObject]
                    let projectName = project.key
                    let projectTimestamp = dict["timestamp"] as! Int
                    let projectDetail = dict["description"] as! String
                    let newProject = ProjectDetail(thisName: projectName, thisTimestamp: projectTimestamp, thisDetail: projectDetail)
                    projects.append(newProject)
                }
                completionHandler(projects)
            }
        }

    }
}
