//
//  ChartsPresenter.swift
//  Improcess
//
//  Created by MuMhu on 14/3/2562 BE.
//  Copyright (c) 2562 Kittitat Boonkarn. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol ChartsPresentationLogic
{
    func presentChart(response: Charts.ChartsData.Response)
    func presentDefect(response: Charts.DefectData.Response)
}

class ChartsPresenter: ChartsPresentationLogic
{
    
    weak var viewController: ChartsDisplayLogic?
    
    // MARK: Do something
    
    func presentChart(response: Charts.ChartsData.Response)
    {
        let viewmodel = Charts.ChartsData.ViewModel(predition: response.predition)
        viewController?.displayChart(viewModel: viewmodel)
    }
    
    func presentDefect(response: Charts.DefectData.Response){
        let viewmodel = Charts.DefectData.ViewModel(defectQuantity: response.defectQuantity)
        viewController?.displayDefect(viewModel: viewmodel)
    }
}
