//
//  ChartsModels.swift
//  Improcess
//
//  Created by MuMhu on 14/3/2562 BE.
//  Copyright (c) 2562 Kittitat Boonkarn. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

enum Charts
{
    // MARK: Use cases
    
    enum ChartsData
    {
        struct Request
        {
            
        }
        struct Response
        {
            var predition: [PredictionChartsData]
        }
        struct ViewModel
        {
            var predition: [PredictionChartsData]
        }
    }
    
    enum DefectData
    {
        struct Request
        {
            
        }
        struct Response
        {
            var defectQuantity: [DefectChartData]
        }
        struct ViewModel
        {
            var defectQuantity: [DefectChartData]
        }
    }
}

struct PredictionChartsData{
    var taskName: String
    var predictionData: Float
    var timestamp: Int
    
    init(name: String, prediction: Float, timestamp: Int) {
        self.taskName = name
        self.predictionData = prediction
        self.timestamp = timestamp
    }
}

struct DefectChartData{
    var taskName: String
    var numberOfDefects: Int
    var timestamp: Int
    
    init(name: String,numberOfDefects: Int, timestamp: Int) {
        self.taskName = name
        self.numberOfDefects = numberOfDefects
        self.timestamp = timestamp
    }
}
