//
//  ChartsInteractor.swift
//  Improcess
//
//  Created by MuMhu on 14/3/2562 BE.
//  Copyright (c) 2562 Kittitat Boonkarn. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol ChartsBusinessLogic
{
    func getChartData()
    func getDefectData()
    func getAllTaskProducivility()
    var projectDetail: ProjectDetail? {get set}
    var tasks: [ProjectTask]? {get set}
}

protocol ChartsDataStore
{
    var projectDetail: ProjectDetail? {get set}
    var tasks: [ProjectTask]? {get set}
}

class ChartsInteractor: ChartsBusinessLogic, ChartsDataStore
{
    var tasks: [ProjectTask]?
    var projectDetail: ProjectDetail?
    
    var presenter: ChartsPresentationLogic?
    var worker: ChartsWorker?
    //var name: String = ""
    
    // MARK: Do something
    
    func getChartData(){
        worker = ChartsWorker()
        let filtedList = tasks?.filter{ $0.status == "Close"}
        
        worker?.getChartData(project: projectDetail!, tasks: filtedList!, completionHandler: { (list) in
            let response = Charts.ChartsData.Response(predition: list)
            self.presenter?.presentChart(response: response)
        })
        
    }
    
    func getDefectData(){
        worker = ChartsWorker()
        
        let filtedList = tasks?.filter{ $0.status == "Close"}
        worker?.getDefectData(project: projectDetail!, tasks: filtedList!, completionHandler: { (list) in
            let response = Charts.DefectData.Response(defectQuantity: list)
            self.presenter?.presentDefect(response: response)
        })
    }
    
    func getAllTaskProducivility(){
        worker = ChartsWorker()
        
        let filtedList = tasks?.filter{ $0.status == "Close"}
        
        worker?.getAllTasksProducivility(project: projectDetail!, tasks: filtedList!, completionHandler:  { (lists) in
            let response = ProducivilityPage.Producivility.Response(tasksProducivility: lists)
            self.presenter?.presentProducivility(response: response)
        })
    }
    
}


