//
//  SignupPageWorker.swift
//  Improcess
//
//  Created by MuMhu on 15/10/2561 BE.
//  Copyright (c) 2561 Kittitat Boonkarn. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit
import FirebaseAuth

class SignupPageWorker
{
    func signupID(username: String!, password: String!, ComplementHandler: @escaping (Bool, String?) -> Void)
    {
        Auth.auth().createUser(withEmail: username, password: password) { (user, error) in
            if error != nil {
                let errorMessage = error?.localizedDescription
                ComplementHandler(true,errorMessage)
            }
            else{
                ComplementHandler(false,nil)
            }
        }
    }
}
