//
//  SignupPageInteractor.swift
//  Improcess
//
//  Created by MuMhu on 15/10/2561 BE.
//  Copyright (c) 2561 Kittitat Boonkarn. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol SignupPageBusinessLogic
{
    func signup(request: SignupPage.SignupData.Request)
}

protocol SignupPageDataStore
{
    //var name: String { get set }
}

class SignupPageInteractor: SignupPageBusinessLogic, SignupPageDataStore
{
    var presenter: SignupPagePresentationLogic?
    var worker: SignupPageWorker?
    //var name: String = ""
    
    // MARK: Do something
    
    func signup(request: SignupPage.SignupData.Request)
    {
        if request.username == "" || request.password == "" {
            let response = SignupPage.SignupData.Response(isError: true, errorMessage: "Fields may not be empty!")
            self.presenter?.presentSignupResult(response: response)
        }
        
        worker = SignupPageWorker()
        worker?.signupID(username: request.username, password: request.password, ComplementHandler: { (isError, errorMessage) in
            let response = SignupPage.SignupData.Response(isError: isError, errorMessage: errorMessage)
            self.presenter?.presentSignupResult(response: response)
        })
    }
}
