//
//  SignupPageRouter.swift
//  Improcess
//
//  Created by MuMhu on 15/10/2561 BE.
//  Copyright (c) 2561 Kittitat Boonkarn. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

@objc protocol SignupPageRoutingLogic
{
    func routeToLoginPage(segue: UIStoryboardSegue?)
}

protocol SignupPageDataPassing
{
    var dataStore: SignupPageDataStore? { get }
}

class SignupPageRouter: NSObject, SignupPageRoutingLogic, SignupPageDataPassing
{
    weak var viewController: SignupPageViewController?
    var dataStore: SignupPageDataStore?
    
    // MARK: Routing
    
    func routeToLoginPage(segue: UIStoryboardSegue?)
    {
      if let segue = segue {
        let destinationVC = segue.destination as! LoginPageViewController
        _ = destinationVC.router!.dataStore!
      } else {
        let storyboard = UIStoryboard(name: "Main", bundle: nil)
        let destinationVC = storyboard.instantiateViewController(withIdentifier: "LoginPageViewController") as! LoginPageViewController
        _ = destinationVC.router!.dataStore!
      }
    }
    
    // MARK: Navigation
    
//    func navigateToSomewhere(source: SignupPageViewController, destination: LoginPageViewController)
//    {
//      source.show(destination, sender: nil)
//    }
    
    // MARK: Passing data
    
    //func passDataToSomewhere(source: SignupPageDataStore, destination: inout SomewhereDataStore)
    //{
    //  destination.name = source.name
    //}
}
