//
//  TemplatesPageWorker.swift
//  Improcess
//
//  Created by MuMhu on 7/11/2561 BE.
//  Copyright (c) 2561 Kittitat Boonkarn. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit
import Firebase

class TemplatesPageWorker
{
    func requestTemplatesFromFirebase(completionHandler: @escaping([TemplateForm]) -> Void)
    {
        var templates = [TemplateForm]()
        Database.database().reference().child("templates").observe(.value) { (snapshot) in
            if let templatesDic = snapshot.value as? [String : AnyObject]{
                for template in templatesDic{
                    let dict = template.value as! [String: AnyObject]
                    let name = template.key
                    let detail = dict["description"] as! String
                    let imagePath = dict["imagePath"] as! String
                    let newTemplate = TemplateForm(templateName: name, templateImagePath: imagePath, templateDetail: detail)
                    templates.append(newTemplate)
                }
            }
            completionHandler(templates)
        }
        
    }
    
    func createProjectWithSelectedTemplate(projectName:String, template: String){
        let uid = Auth.auth().currentUser?.uid
        Database.database().reference().child("templates").child(template).observe(.value) { (snapshot) in
            Database.database().reference().child(uid!).child("projects").child(projectName).setValue(snapshot.value)
        }
    }
}
