//
//  TemplatesPageModels.swift
//  Improcess
//
//  Created by MuMhu on 7/11/2561 BE.
//  Copyright (c) 2561 Kittitat Boonkarn. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

enum TemplatesPage
{
    // MARK: Use cases
    enum Template
    {
        struct Request
        {
        }
        struct Response
        {
            var templates: [TemplateForm]?
        }
        struct ViewModel
        {
            var templates: [TemplateForm]?
        }
    }

}

struct TemplateForm{
    var templateName: String?
    var templateImagePath: String?
    var templateDetail: String?
}

