//
//  TemplatesPageInteractor.swift
//  Improcess
//
//  Created by MuMhu on 7/11/2561 BE.
//  Copyright (c) 2561 Kittitat Boonkarn. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol TemplatesPageBusinessLogic
{
    func requestTemplates()
    func createProject(template:String)
}

protocol TemplatesPageDataStore
{
    var proJectName: String? { get set }
    var proJectDetails: String? { get set }
}

class TemplatesPageInteractor: TemplatesPageBusinessLogic, TemplatesPageDataStore
{
    var presenter: TemplatesPagePresentationLogic?
    var worker: TemplatesPageWorker?
    var proJectName: String?
    var proJectDetails: String?
    //var name: String = ""
    
    // MARK: Do something
    
    func requestTemplates()
    {
        worker = TemplatesPageWorker()
        worker?.requestTemplatesFromFirebase(completionHandler: { (template) in
            let response = TemplatesPage.Template.Response(templates: template)
            self.presenter?.presentTemplates(response: response)
        })
    }
    
    func createProject(template: String) {
        worker = TemplatesPageWorker()
        worker?.createProjectWithSelectedTemplate(projectName: proJectName!, template: template)
    }
}

