//
//  TemplatesPagePresenter.swift
//  Improcess
//
//  Created by MuMhu on 7/11/2561 BE.
//  Copyright (c) 2561 Kittitat Boonkarn. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol TemplatesPagePresentationLogic
{
    func presentTemplates(response: TemplatesPage.Template.Response)
}

class TemplatesPagePresenter: TemplatesPagePresentationLogic
{
    weak var viewController: TemplatesPageDisplayLogic?
    
    // MARK: Do something
    
    func presentTemplates(response: TemplatesPage.Template.Response)
    {
        let viewModel = TemplatesPage.Template.ViewModel(templates: response.templates)
        viewController?.displayTemplates(viewModel: viewModel)
    }
}
